#include <stdio.h>

void main(){
	int world=7;
	int number=1;

	printf("World sector: %d",world);

	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
	printf("Hello world!\n");
}
